# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib {
  H:/Spring2015/EECS443/project_1/project_1.srcs/sources_1/imports/example/UART_TX_CTRL.vhd
  H:/Spring2015/EECS443/project_1/project_1.srcs/sources_1/imports/example/RGB_controller.vhd
  H:/Spring2015/EECS443/project_1/project_1.srcs/sources_1/imports/example/debouncer.vhd
  H:/Spring2015/EECS443/project_1/project_1.srcs/sources_1/imports/example/GPIO_Demo.vhd
}
read_xdc H:/Spring2015/EECS443/project_1/project_1.srcs/constrs_1/imports/example/Nexys4_Master.xdc
set_property used_in_implementation false [get_files H:/Spring2015/EECS443/project_1/project_1.srcs/constrs_1/imports/example/Nexys4_Master.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/Spring2015/EECS443/project_1/project_1.cache/wt [current_project]
set_property parent.project_dir H:/Spring2015/EECS443/project_1 [current_project]
catch { write_hwdef -file GPIO_demo.hwdef }
synth_design -top GPIO_demo -part xc7a100tcsg324-1
write_checkpoint GPIO_demo.dcp
report_utilization -file GPIO_demo_utilization_synth.rpt -pb GPIO_demo_utilization_synth.pb
